# fly.toml app configuration file generated for youtube-2024 on 2024-02-05T14:04:23+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

kill_signal = "SIGTERM"
kill_timeout = 120

app = 'youtube-2024'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
